# Generated by Django 5.1.1 on 2024-11-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConnXt', '0002_alter_studentinfo_student_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
