# Generated by Django 5.1.1 on 2024-11-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConnXt', '0004_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='job_date',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='job_location',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='job_questions',
            field=models.TextField(default='Required Questions:'),
            preserve_default=False,
        ),
    ]
