# Generated by Django 5.1.1 on 2024-11-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConnXt', '0005_remove_jobposting_job_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='essay_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
